define(function() {
    'use strict';

    return {
        aboutUtilities: 'Future utilities is a custom application designed to help you accomplish administrative or scientific tasks in the Vanderbilt Vaccine Center (VVC), including updating content for our websites. Using the features shown in the pulldown menus, you can search inventories or databases, manage documents such as Material Transfer Agreements and Travel, place orders in the GoCore, obtain software, or update your publications. The VVC utility tab allows users to update web content and VVC databases.',
        aboutPublications: 'Synchronize your utilities account with pub med. Follow the step by step process to pull all your publications from pub med. The data you pull down will be used to present your publications on the VVC website.',
        aboutCrowelab: 'Our group uses a very broad array of techniques including molecular and cellular biology, state-of-the-art imaging and flow cytometry, bioinformatics, and bioengineering approaches to attack the scientific problems that are of interest to us. Our philosophy is to work on major human pathogens - we study model systems only when the direct study of the primary pathogen in humans is not feasible at a definitive level. Current studies center on respiratory syncytial virus, human metapneumovirus, rotavirus, HIV, influenza, and vaccinia virus.',
        aboutAdminCore: 'The Administrative Office manages the fiscal, operational, and human resource activities of the Vanderbilt Vaccine Center, focusing on financial matters, grants, center events, international programs, staffing, and communications. The Administrative Office prepares regular financial updates on contracts and is responsible for pre and post-award management of the VVC\'s contracts and grants (federal and non-federal sources), including subcontract management. The Administrative Office also has excellent online systems for maintaining control of expenditures, including online ordering, invoicing, reconciliation, and budgets.',
        aboutFlowCore: 'The Flow Cytometry Core Lab enjoys state-of-the-art digital instrumentation maintained at the highest standards attainable. This quality control allows researchers to sort cells at high efficiency and purity under the proper conditions or to run analytical experiments with as many as 17 different fluorochromes simultaneously. The Flow Cytometry Core is dedicated to providing the best service and training possible to ensure the best results attainable for research scientists and physicians.',
        aboutGocore: 'The VVC Molecular Biology and Protein Expression Core (aka GoCore) is an internal unit of the Vanderbilt Vaccine Center and staffed by two senior and two junior Research Assistants. The Core provides several services to the researchers including DNA purification, protein expression and purification, assistance in hybridoma generation, Sanger sequencing of hybridoma V genes and more. Service requests, notifications of request fulfillment and relevant experimental data, are handled through custom web apps developed in house. By providing assistance in routine and time-consuming tasks, the Core enables researchers to spend more of their in detailed characterization of the generated antibodies.',
        aboutImmunologyCore: 'The Immunology Core provides a wide-range of support and assays to assist investigators in their research with a primary interest in assessing cellular immune responses during clinical trials. We strive to assist investigators with sample processing, storage, shipping, documentation, assay design, assay development, and evaluation of immune responses. Our dedicated staff can provide consulation to investigators on the types of immune assays to choose for clinical trial monitoring and data interpretation. It is the goal of the core to monitor immune responses during clinical trials using the latest advances in technology and provide practical applications of this technology to evaluating immune responses. We continue to develop new immune monitoring technology with industry and academic collaborators. The immunology core has extensive experience in assay development and optimization and will assist in the selection of appropriate assays and antigens during the protocal/developmental phase of a study or trial. A brief description of assays are listed below, however; each study design will have unique features that require careful consideration and development and optimization prior to testing samples. Thus, specific assay conditions are not described in detail.',
        aboutPolackLab: 'After working as a physician scientist in the U.S. for over 10 years, Dr. Polack returned home to Argentina in 2003 to create the Fundación INFANT (translation INFANT Foundation), a research foundation in Buenos Aires, and to contribute to the development of science in South America, especially in Argentina. Dr. Polack is a leading scientist in the field of respiratory virus virology and immunology, and he has received numerous awards throughout his career, including the 2010 E. Mead Johnson Award for Excellence in Pediatric Research, awarded by the Society for Pediatric Research.',
        aboutTechCore: 'The technology core assists the VVC with server administration, database optimization, and development of custom software such as the applications on this website. We work closely with our scientists to solve problems with tech solutions.'
    }
});